name: Defect Creation in LK

on:
  issues:
    types:
    - opened
  
jobs:
  create-defect:
    environment: NACL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create defect
        uses: PVSCDemo/github-actions-dev/createCard@v0.3
        with:
          host: ${{secrets.LEANKIT_URL}}
          apiToken: ${{secrets.LEANKIT_API}}
          boardId: ${{secrets.BOARD_ID}}
          title: ${{github.event.issue.title}}
          customId: GitHub Issue #${{github.event.issue.number}}
          externalLink: ${{github.event.issue.html_url}}
          typeId: ${{secrets.DEFECT_TYPE}}
